---
# tasks file for app
#
- name: Creamos un namespace llamado example (1)
  shell: "export KUBECONFIG=/home/azureuser/.kube/config;kubectl create namespace example"
  register: kubeadm_create_namespace
  become: false

- name: Salida de la creacion del create de namespace example (1)
  debug:
    msg: "{{ kubeadm_create_namespace.stdout }}"

- name: Comprobamos que se ha creado el namespace (2)
  shell: "export KUBECONFIG=/home/azureuser/.kube/config;kubectl get namespaces"
  register: kubeadm_check_namespace
  become: false

- name: Salida de la comprobacion del namespace (2)
  debug:
    msg: "{{ kubeadm_check_namespace.stdout }}"

## Copiando archivo despliegue aplicacion al master ##
- name: Copiando template aplicacion
  template:
    src: myapp.j2
    dest: /home/azureuser/aplicacion.yaml
    owner: azureuser
    group: users
    mode: '0644'

- name:  Crear recursos de la aplicación (3)
  shell: "export KUBECONFIG=/home/azureuser/.kube/config;kubectl apply -f /home/azureuser/aplicacion.yaml"
  register: kubeadm_recursos_namespace
  become: false

- name: Salida del despliegue de la aplicacion (3)
  debug:
    msg: "{{ kubeadm_recursos_namespace.stdout }}"

- name: Esperamos 1 minuto para crear recursos de la aplicacion
  pause:
    minutes: 1

- name:  Consultar los recursos deployment,pods,services (4)
  shell: "export KUBECONFIG=/home/azureuser/.kube/config;kubectl get deployment,pods,pv,pvc -n example"
  register: kubeadm_recursos_namespace

- name: Salida de la consulta de recursos (4)
  debug:
    msg: "{{ kubeadm_recursos_namespace.stdout }}"
