  
- debug:
        msg: "Comando para el alta de los workers: {{ comando_join_worker }}"
  when: comando_join_worker is defined  

- name: Habilitamos los puertos necesarios (18) 
  firewalld:
    permanent: true
    zone: public
    port: "{{ item.port }}"
    state: "{{ item.state }}"
  loop:
    "{{ port_worker }}"
  become: yes

- name: Reiniciando el servicio Firewalld (18)
  systemd:
    name: firewalld
    state: restarted
  become: yes

- name: Reinicio del worker antes del join
  reboot:
  become: true

- name: Mostramos el comando de unión del worker al master
  debug:
    msg: "Se ejecutará: {{ comando_join_worker }}"

- name: En 60 segundos ejecutamos el comando del join en el worker
  pause:
    seconds: 60


- name: Unimos el Worker al clúster Kubernetes (19)
  shell: " {{ comando_join_worker }}"
  register: kubeadm_join
  become: true

- name: Resultado de la unión del Worker al clúster
  debug:
    msg: "{{ kubeadm_join.stdout_lines }}"

- name: Reinicio del worker despues del join
  reboot:
  become: true
